Add container image attestation verification support
Azure-Samples/azure-cleanroom-samples pull request #9
Opened 2024-11-25 08:35 UTC by anrdesai

## Purpose

Adds support for verification if GitHub attestations of container images referenced in the deployment template. This helps tie the image back to a commit and the workflow from which the container image was built.

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2024-11-25 08:53 UTC, PhaniChiruvolu commented on docker/Dockerfile.azure-cleanroom-samples
> +    && mkdir -p -m 755 /etc/apt/keyrings \
>mkdir -p -m 755 /etc/apt/keyrings [](http://example.com/codeflow?start=7&length=33)

This is already being done above for other keyrings. Instead of adding another keyring entry here, please add the github gpg along with docker and msft above.

2024-11-25 08:53 UTC, anantshankar17 commented on scripts/contract/verify-deployment-artefacts.ps1
> +        Select-Object -Unique
Should we segregate the mcr.microsoft.com/cleanroom images and the others ?
The problem is the app container not getting attested is something the 2 parties need to resolve.

2024-11-25 08:54 UTC, PhaniChiruvolu commented on docker/Dockerfile.azure-cleanroom-samples
> +    && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
>wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null [](http://example.com/codeflow?start=7&length=137)

Use curl directly and add this to the set of commands at line 14?

2024-11-25 08:58 UTC, PhaniChiruvolu commented on docker/Dockerfile.azure-cleanroom-samples
> +RUN (type -p wget >/dev/null || (apt update && apt-get install wget -y)) \
>type -p wget >/dev/null || (apt update && apt-get install wget -y [](http://example.com/codeflow?start=5&length=65)

I am assuming we don't need to install wget if you use curl for the gpg.

2024-11-25 09:00 UTC, PhaniChiruvolu commented on docker/Dockerfile.azure-cleanroom-samples
> +    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.li
>echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \ [](http://example.com/codeflow?start=7&length=208)

Shall we move to github.list like docker.list and use that instead of inlining it here?

2024-11-25 09:02 UTC, anantshankar17 commented on scripts/contract/verify-deployment-artefacts.ps1
> +        CheckLastExitCode
Should we bailout here or print and continue and set the final result to be failed ?

Since the customer application will also be included here, just want to leave it to the parties, if gh attest doesn't work for their app.

2024-11-25 09:04 UTC, PhaniChiruvolu commented on scripts/contract/verify-deployment-artefacts.ps1
> +    )
Instead of passing in an ACI template, it would be more useful to pass in container image list. That way, the caller can extract the containers from ACI/AKS and just send in the image@hash into this routine.

2024-11-25 09:06 UTC, PhaniChiruvolu commented on scripts/contract/verify-deployment-artefacts.ps1
> +function Verify-Template {
Maybe something like Assert/Confirm - CleanroomAttestation?

2024-11-25 09:06 UTC, PhaniChiruvolu commented on scripts/contract/confirm-deployment-artefacts.ps1
> +. $PSScriptRoot/verify-deployment-artefacts.ps1
Move the helper routine into ../common and add it to common.psm1 instead?

2024-11-25 09:09 UTC, PhaniChiruvolu commented on scripts/contract/confirm-deployment-artefacts.ps1
> +gh auth login --web
This is looking odd here, any reason this is not a part of the helper function?

2024-11-25 09:16 UTC, PhaniChiruvolu commented on scripts/contract/confirm-deployment-artefacts.ps1
Do we really need to create a directory for one file?

2024-11-25 09:17 UTC, PhaniChiruvolu commented on scripts/contract/confirm-deployment-artefacts.ps1
> +    --governance-client $cgsClient | Out-File "$artefactsDir/cleanroom-arm-template.json"
>$artefactsDir/cleanroom-arm-template.json [](http://example.com/codeflow?start=47&length=41)

Instead of creating a directory here, can we prefix $contractId and leave the json in the privateDir?

2024-11-25 09:18 UTC, PhaniChiruvolu commented on scripts/contract/confirm-deployment-artefacts.ps1
> +Verify-Template -deploymentTemplatePath "$artefactsDir/cleanroom-arm-template.json"
If you take the other comment about making this function agnostic to ACI template, the logic to extract containers can come locally here and we can pass in the image list to the helper function.

2024-11-25 09:19 UTC, PhaniChiruvolu commented on scripts/contract/confirm-deployment-artefacts.ps1
> +gh auth login --web
Also, what is the login step here? Does it launch a browser? Or is it anonymous?

2024-11-25 09:20 UTC, PhaniChiruvolu commented
> # TODO: Logic to showcase policy verification is pending.

Will you be adding az confcom here?

---
Refers to: scripts/contract/confirm-deployment-artefacts.ps1:63 in 2266073. [](commit_id = 22660737920efb744ed5a51874a4b73f14dff79d, deletion_comment = False)

2024-11-25 09:21 UTC, PhaniChiruvolu requested changes
:clock1:

2024-11-25 10:25 UTC, anantshankar17 commented on scripts/contract/verify-deployment-artefacts.ps1
> +    Write-Log Information "All images are built off the commit '$commitId'."
>Write-Log Information "All images are built off the commit '$commitId'." [](http://example.com/codeflow?start=4&length=72)

gives the refs without git: 
curl [https://github.com/Azure/azure-cleanroom.git/info/refs?service=git-upload-pack](https://github.com/Azure/azure-cleanroom.git/info/refs?service=git-upload-pack) --output scratch.txt

From above, we can find out the tag 2.0.0 using the commit id from the gh attestation.

We can for now assume that the tag can only be 2.0.0. Later we can add the tag to the deployment template also, in the az cli and then do the validation for that value of the tag that the one in template and the derived is the same.

2024-11-26 06:57 UTC, anrdesai commented on scripts/contract/confirm-deployment-artefacts.ps1
> +gh auth login --web
This isn't anonymous and opens a web browser for login. gh attestation does not support anonymous verification

2024-11-26 18:13 UTC, anrdesai commented on docker/Dockerfile.azure-cleanroom-samples
> +RUN (type -p wget >/dev/null || (apt update && apt-get install wget -y)) \
Yes, we no longer need wget.

2024-11-26 18:16 UTC, anrdesai commented on scripts/contract/confirm-deployment-artefacts.ps1
Cleaned up

2024-11-26 18:18 UTC, anrdesai commented on docker/Dockerfile.azure-cleanroom-samples
> +    && mkdir -p -m 755 /etc/apt/keyrings \
Resolved.

2024-11-26 18:19 UTC, anrdesai commented on docker/Dockerfile.azure-cleanroom-samples
> +    && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
Resolved

2024-11-26 18:19 UTC, anrdesai commented on docker/Dockerfile.azure-cleanroom-samples
> +    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.li
Resolved

2024-11-26 18:20 UTC, anrdesai commented on scripts/contract/verify-deployment-artefacts.ps1
> +function Verify-Template {
Changed this to Assert-CleanroomAttestation.

Resolved

2024-11-26 18:20 UTC, anrdesai commented on scripts/contract/confirm-deployment-artefacts.ps1
> +. $PSScriptRoot/verify-deployment-artefacts.ps1
Resolved

2024-11-26 18:22 UTC, anrdesai commented on scripts/contract/confirm-deployment-artefacts.ps1
> +gh auth login --web
Wondering if this is better suited as an upfront candidate, similar to az login? Otherwise, this ends up prompting for login every single time the script is called.

2024-11-26 18:22 UTC, anrdesai commented on scripts/contract/confirm-deployment-artefacts.ps1
> +    --governance-client $cgsClient | Out-File "$artefactsDir/cleanroom-arm-template.json"
Resolved

2024-11-26 18:25 UTC, anrdesai commented
> # TODO: Logic to showcase policy verification is pending.

The plan was to add it in, but we found an issue where our ARM template has images named mcr.microsoft..., but the policy is generated with the base ACR name instead.

Will pick that change up subsequently once we have identified a fix for it

---
In reply to: [2497376542](https://github.com/Azure-Samples/azure-cleanroom-samples/pull/9#issuecomment-2497376542) [](http://example.com/codeflow?ancestors=2497376542)

---
Refers to: scripts/contract/confirm-deployment-artefacts.ps1:63 in 2266073. [](commit_id = 22660737920efb744ed5a51874a4b73f14dff79d, deletion_comment = False)

2024-11-26 18:26 UTC, anrdesai commented on scripts/contract/verify-deployment-artefacts.ps1
> +    Write-Log Information "All images are built off the commit '$commitId'."
Used a combination of gh apis to achieve the same.

Resolved

2024-11-27 06:04 UTC, anantshankar17 commented on scripts/contract/verify-deployment-artefacts.ps1
> +    Write-Log Information "All images are built off the commit '$commitId'."
@anrdesai Hey, can you also do the validation for the below?:

So the now that you have the tag from the image, you can read the tag from the template and assert they are the same, after you check the commits are based off the same one.

You can look for the tag in the template: accr-version and assume the value if 2.0.0 if the tag is not present.

>>>>
We can for now assume that the tag can only be 2.0.0. That we can assert with the value derived above.

Later we can add the tag to the deployment template also, in the az cli and then do the validation for that value of the tag that the one in template and the derived is the same.

2024-11-27 06:11 UTC, anantshankar17 commented on scripts/contract/verify-deployment-artefacts.ps1
> +    $repo = "Azure/azure-cleanroom-private"
>Azure/azure-cleanroom-private [](http://example.com/codeflow?start=13&length=29)

why is this -private ??

2024-12-02 05:51 UTC, PhaniChiruvolu commented on docker/Dockerfile.azure-cleanroom-samples
>  FROM docker-azcli-base AS samples-base
Please add a new line before the FROM to make it clear that the current stage has completed.

2024-12-02 05:56 UTC, PhaniChiruvolu commented on scripts/common/verify-deployment-artefacts.ps1
> +function Assert-CleanroomAttestation {
>Assert-CleanroomAttestatio [](http://example.com/codeflow?start=9&length=26)

Rename file to be the same as the function name?

2024-12-02 05:58 UTC, PhaniChiruvolu commented on scripts/contract/confirm-deployment-artefacts.ps1
> +$deploymentTemplate = Get-Content "$privateDir/$contractId-cleanroom-arm-template.json" | ConvertFrom-Json
>"$privateDir/$contractId-cleanroom-arm-template.json" [](http://example.com/codeflow?start=34&length=53)

Nit: Store this in a variable instead of generating the name at 2 places?

2024-12-02 06:00 UTC, PhaniChiruvolu commented on scripts/common/verify-deployment-artefacts.ps1
> +    $workflowRef = "refs/heads/main"
Add a comment explaining these and a link to the repo? Also, not yours, but we should update the code repo readme to explicitly capture details about the workflow generating the cleanroom containers.

2024-12-02 06:02 UTC, PhaniChiruvolu commented on scripts/common/verify-deployment-artefacts.ps1
> +    }
Won't this reflect as a native command error and automatically exit per the settings in line 12-13?

2024-12-02 06:06 UTC, PhaniChiruvolu commented on scripts/common/verify-deployment-artefacts.ps1
> +        [string]$privateDir = "$samplesRoot/demo-resources/private"
These are looking very odd here - have a (mandatory) $tempDir parameter instead that the caller has to pass in?

2024-12-02 06:07 UTC, PhaniChiruvolu commented on scripts/common/verify-deployment-artefacts.ps1
> +
Won't this reflect as a native command error and automatically exit per the settings in line 12-13?

2024-12-02 06:09 UTC, PhaniChiruvolu commented on scripts/common/verify-deployment-artefacts.ps1
> +    gh attestation trusted-root > "$privateDir/trusted_root.jsonl"
>"$privateDir/trusted_root.jsonl" [](http://example.com/codeflow?start=34&length=32)

Nit: Store this in a variable instead of generating the name at 2 places?

2024-12-02 06:10 UTC, PhaniChiruvolu commented on scripts/common/verify-deployment-artefacts.ps1
> +        rm -f "$privateDir/$digest.jsonl"
>"$privateDir/$digest.jsonl" [](http://example.com/codeflow?start=14&length=27)

Nit: Store this in a variable instead of generating the name at multiple places?

2024-12-02 06:10 UTC, PhaniChiruvolu commented on scripts/common/verify-deployment-artefacts.ps1
> +            Write-Log Error "Images in the deployment template are not from the latest commit."
>latest [](http://example.com/codeflow?start=80&length=6)

expected?

2024-12-02 06:11 UTC, PhaniChiruvolu commented on scripts/common/verify-deployment-artefacts.ps1
> +            Write-Log Error "Images in the deployment template are from different workflows."
>are from different workflows [](http://example.com/codeflow?start=63&length=28)

are not generated by the expected workflow 'path'

2024-12-02 06:12 UTC, PhaniChiruvolu commented on scripts/common/verify-deployment-artefacts.ps1
> +            Write-Log Error "Images in the deployment template are from different branches."
>are from different branches. [](http://example.com/codeflow?start=63&length=28)

are not generated from the expected branch 'branchref'

2024-12-02 06:12 UTC, PhaniChiruvolu commented on scripts/common/verify-deployment-artefacts.ps1
> +    Write-Log Information "All images are built off the commit '$commitId'."
>'$commitId' [](http://example.com/codeflow?start=63&length=11)

add workflow and branchref in the message?

2024-12-02 06:14 UTC, PhaniChiruvolu commented on scripts/contract/confirm-deployment-artefacts.ps1
> +    [string]$artefactsDir = "$privateDir/$contractId-artefacts"
Stale?

2024-12-02 06:17 UTC, PhaniChiruvolu commented
> # TODO: Logic to showcase policy verification is pending.

:cry:

---
In reply to: [2501648187](https://github.com/Azure-Samples/azure-cleanroom-samples/pull/9#issuecomment-2501648187) [](http://example.com/codeflow?ancestors=2501648187,2497376542)

---
Refers to: scripts/contract/confirm-deployment-artefacts.ps1:63 in 2266073. [](commit_id = 22660737920efb744ed5a51874a4b73f14dff79d, deletion_comment = False)

2024-12-02 06:19 UTC, PhaniChiruvolu approved these changes
:shipit:

2024-12-02 08:06 UTC, anantshankar17 commented on scripts/contract/confirm-deployment-artefacts.ps1
> +    [string]$privateDir = "$samplesRoot/demo-resources/private",
Same comment as the other file. This can be any temp directory, not necessarily the repo path, right ?

2024-12-02 09:21 UTC, anrdesai commented on scripts/contract/confirm-deployment-artefacts.ps1
> +gh auth login --web
Resolving as we no longer need a login

2024-12-02 09:23 UTC, anrdesai commented on scripts/contract/verify-deployment-artefacts.ps1
> +    $repo = "Azure/azure-cleanroom-private"
Started off verifying attestations published by the private repo, moved these to the public one now

2024-12-02 10:56 UTC, anrdesai commented on scripts/contract/confirm-deployment-artefacts.ps1
> +    [string]$privateDir = "$samplesRoot/demo-resources/private",
This was just to keep it in parity with other top-level scripts

2024-12-02 17:55 UTC, anantshankar17 approved these changes

2024-12-03 05:27 UTC, merged